# Generated by Django 5.2.6 on 2025-10-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='condition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
