# Generated by Django 5.2.6 on 2025-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badge_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='progress',
            field=models.JSONField(default=dict),
        ),
    ]
