# Generated by Django 5.2.6 on 2025-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_userbadge_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
