# Generated by Django 5.2.6 on 2025-09-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fav_guard',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fav_passage',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fav_submission',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
