# Generated by Django 5.2.6 on 2025-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_fav_guard_and_more'),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, to='badges.badge'),
        ),
    ]
