# Generated by Django 5.2.6 on 2025-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fav_guard',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fav_passage',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fav_submission',
            field=models.CharField(default='', max_length=25),
        ),
    ]
