# Generated by Django 5.2.6 on 2025-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bronze_medal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gold_medal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='silver_medal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='victory',
            field=models.IntegerField(default=0),
        ),
    ]
