# Generated by Django 5.2.6 on 2025-11-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_admin_alter_customuser_fav_guard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=30),
        ),
    ]
