# Generated by Django 5.2.6 on 2025-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bronze_medal_customuser_gold_medal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='belt',
            field=models.CharField(choices=[('Blanche', 'Blanche'), ('Bleue', 'Bleue'), ('Violette', 'Violette'), ('Marron', 'Marron'), ('Noire', 'Noire')], default='1', max_length=10),
        ),
    ]
