# Generated by Django 5.2.6 on 2025-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_belt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='belt',
            field=models.CharField(choices=[('White', 'White'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Black', 'Black')], default='White', max_length=10),
        ),
    ]
