# Generated by Django 5.2.6 on 2025-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='keyword',
            field=models.CharField(default='TEST', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drill',
            name='accomplish',
            field=models.BooleanField(default=False),
        ),
    ]
